tasks_list = ['Deep fake', 'HDRI', 'UVLayout', 'Анимировать 3D-персонажа', 'Анимировать лицо', 'Визуализировать данные',
              'Восстановить', 'Восстановить видео', 'Восстановить изображение', 'Выровнять голос',
              'Деформировать 3D-объект', 'Добавить взаимодействие в 3D-сцену', 'Добавить водяной знак',
              'Добавить объект', 'Заменить небо', 'Заменить объект', 'Играть', 'Извлечь голос из аудио',
              'Изменить время суток', 'Изменить голос', 'Изменить позу тела', 'Изменить фон', 'Интерполяция кадров',
              'Локализовать', 'Маскироваться', 'Монетизировать', 'Найти вдохновение', 'Найти объект',
              'Найти похожие 3D', 'Найти референсы', 'Найти текстуру', 'Написать e-mail', 'Написать код',
              'Написать пост', 'Написать поэму', 'Написать статью', 'Настроить Point Cloud', 'Описание товара',
              'Описать видео', 'Описать изображение', 'Отредактировать видео', 'Отредактировать видео по референсу',
              'Отредактировать изображение', 'Отредактировать изображение по параметрам',
              'Отредактировать изображение по референсу', 'Отредактировать изображение с наброском',
              'Отредактировать изображение с текстом', 'Отследить позу тела', 'Отфильтровать Point Cloud',
              'Перекрасить', 'Перенести стиль', 'Поделиться искусством', 'Поиск', 'Получить аналитику',
              'Преобразовать речь в текст', 'Преобразовать текст в речь', 'Применить объекты к видео',
              'Применить эффекты к видео', 'Применить эффекты к изображению', 'Проанализировать 3D-сцену',
              'Проанализировать PDF', 'Проанализировать аудио', 'Проанализировать видео', 'Проанализировать документ',
              'Проанализировать изображение', 'Проанализировать контент', 'Проанализировать сайт',
              'Проверить на плагиат', 'Раскрасить', 'Распознать лицо', 'Распознать текст', 'Расширить изображение',
              'Резюмировать контент', 'Рерайт контента', 'Рерайт статей', 'Сгенерировать музыку', 'Сгенерировать строки',
              'Сегментировать Point Cloud', 'Синтезировать голос', 'Синхронизировать движения губ с видео',
              'Создать 3D-видео', 'Создать 3D-объект', 'Создать 3D-персонажа', 'Создать 3D-сцену', 'Создать 3D-текстуру',
              'Создать аватар', 'Создать анимацию', 'Создать аудио', 'Создать большее количество точек в Point Cloud',
              'Создать видео', 'Создать запрос', 'Создать изображение', 'Создать иконки', 'Создать карту глубины',
              'Создать контент', 'Создать концепт', 'Создать логотип', 'Создать музыку', 'Создать набросок',
              'Создать нюдсы', 'Создать объёмное видео', 'Создать объёмное изображение', 'Создать панораму',
              'Создать портрет', 'Создать презентацию', 'Создать приложение', 'Создать реальную физическую анимацию',
              'Создать сайт', 'Создать таблицу', 'Создать текст', 'Создать текстуру', 'Создать фон', 'Создать чат-бота',
              'Создать эффект slow-mo', 'Создать эффект морфинга', 'Сопоставить аудио с визуалом', 'Стабилизировать видео',
              'Стилизовать', 'Убрать сжатие', 'Убрать шум', 'Убрать шум из аудио',
              'Удалить водяной знак', 'Удалить куски из аудио', 'Удалить объект', 'Удалить фон', 'Удалить фон в видео',
              'Улучшить запрос', 'Улучшить качество видео', 'Улучшить качество изображения', 'Улучшить ночное фото',
              'Улучшить текст', 'Уменьшенить масштаб изображения']


convert_list = ['3D в 3D', '3D в изображение', '3D-текст-3D', '3D+текст в 3D', 'SVG в 3D', 'SVG в SVG', 'Аудио в 3D',
                'Аудио в аудио', 'Аудио в видео', 'Аудио в изображение', 'Аудио в текст', 'Видео в 3D', 'Видео в аудио',
                'Видео в видео', 'Видео в текст', 'Данные в данные', 'Данные в диаграмму', 'Данные в изображение',
                'Данные в текст', 'Игра', 'Изображение в 3D', 'Изображение в аудио', 'Изображение в видео',
                'Изображение в данные', 'Изображение в изображение', 'Изображение в текст', 'Изображение-текст-изображение',
                'Код в код', 'Код в текст', 'Набросок в 3D', 'Набросок в SVG', 'Набросок в видео', 'Набросок в изображение',
                'Сайт в данные', 'Сайт в приложение', 'Текст в 3D', 'Текст в SVG', 'Текст в аудио', 'Текст в видео',
                'Текст в данные', 'Текст в изображение', 'Текст в код', 'Текст в панораму', 'Текст в приложение', 'Текст в сайт',
                'Текст в текст', 'Текст в текстуру', '.']


app_scope_list = ['Дизайн', 'Иллюстрация', 'Реклама и SMM', 'Копирайтинг', 'SEO', 'Блогинг', 'Фотография',
                  'Разработка', 'Разработка игр', 'Чат-бот', 'Музыка', 'Видео', 'Бизнес', 'Учёба', 'Анимация', 'Право',
                  'Каталог', 'Саунд-дизайн', 'Поисковик', 'Электронная коммерция', 'Сторибординг', 'Здоровье',
                  'Развлечение', 'Расширения', 'Производство фильмов', 'Композитинг', 'Концепт-арт', 'Real-Time производство']


app_scope_callback_list = ['design_button_pressed', 'illustration_button_pressed', 'advertising_and_smm_button_pressed',
                           'copywriting_button_pressed', 'seo_button_pressed', 'blogging_button_pressed', 'photography_button_pressed',
                           'development_button_pressed', 'game_development_button_pressed', 'chat_bot_button_pressed', 'music_button_pressed',
                           'video_button_pressed', 'business_button_pressed', 'education_button_pressed', 'animation_button_pressed',
                           'law_button_pressed', 'catalog_button_pressed', 'sound_design_button_pressed', 'search_engine_button_pressed',
                           'e-commerce_button_pressed', 'storyboarding_button_pressed', 'health_button_pressed', 'entertainment_button_pressed',
                           'extensions_button_pressed', 'film_production_button_pressed', 'compositing_button_pressed', 'concept_art_button_pressed',
                           'real-time_production_button_pressed']


convert_callback_list = ['3d_in_3d_button_pressed', '3d_in_image_button_pressed', '3d_text_3d_button_pressed', '3d_plus_text_in_3d_button_pressed',
                         'svg_in_3d_button_pressed', 'svg_in_svg_button_pressed', 'audio_in_3d_button_pressed', 'audio_in_audio_button_pressed',
                         'audio_in_video_button_pressed', 'audio_in_image_button_pressed', 'audio_in_text_button_pressed', 'video_in_3d_button_pressed',
                         'video_in_audio_button_pressed', 'video_in_video_button_pressed', 'video_in_text_button_pressed', 'data_in_data_button_pressed',
                         'data_in_diagram_button_pressed', 'data_in_image_button_pressed', 'data_in_text_button_pressed', 'game_button_pressed',
                         'image_in_3d_button_pressed', 'image_in_audio_button_pressed', 'image_in_video_button_pressed', 'image_in_data_button_pressed',
                         'image_in_image_button_pressed', 'image_in_text_button_pressed', 'image_text_image_button_pressed', 'code_in_code_button_pressed',
                         'code_in_text_button_pressed', 'sketch_in_3d_button_pressed', 'sketch_in_svg_button_pressed', 'sketch_in_video_button_pressed',
                         'sketch_in_image_button_pressed', 'site_in_data_button_pressed', 'site_in_app_button_pressed', 'text_in_3d_button_pressed',
                         'text_in_svg_button_pressed', 'text_in_audio_button_pressed', 'text_in_video_button_pressed', 'text_in_data_button_pressed',
                         'text_in_image_button_pressed', 'text_in_code_button_pressed', 'text_in_panorama_button_pressed', 'text_in_app_button_pressed',
                         'text_in_site_button_pressed', 'text_in_text_button_pressed', 'text_in_texture_button_pressed', 'empty_convert_button_pressed']

tasks_callback_list = ['deep_fake_button_pressed', 'hdri_button_pressed', 'uvlayout_button_pressed', 'animate_3d_character_button_pressed',
                       'animate_face_button_pressed', 'visualize_data_button_pressed', 'restore_button_pressed', 'restore_video_button_pressed',
                       'restore_image_button_pressed', 'align_voice_button_pressed', 'deform_3d_object_button_pressed',
                       'add_interaction_in_3d_scene_button_pressed', 'add_watermark_button_pressed', 'add_object_button_pressed',
                       'replace_sky_button_pressed', 'replace_object_button_pressed', 'play_button_pressed', 'extract_voice_from_audio_button_pressed',
                       'change_time_of_day_button_pressed', 'change_voice_button_pressed', 'change_body_pose_button_pressed',
                       'change_background_button_pressed', 'frame_interpolation_button_pressed', 'localize_button_pressed', 'disguise_button_pressed',
                       'monetize_button_pressed', 'find_inspiration_button_pressed', 'find_object_button_pressed', 'find_similar_3d_button_pressed',
                       'find_references_button_pressed', 'find_texture_button_pressed', 'write_email_button_pressed', 'write_code_button_pressed',
                       'write_post_button_pressed', 'write_poem_button_pressed', 'write_article_button_pressed', 'setup_point_cloud_button_pressed',
                       'product_description_button_pressed', 'describe_video_button_pressed', 'describe_image_button_pressed', 'edit_video_button_pressed',
                       'edit_video_by_reference_button_pressed', 'edit_image_button_pressed', 'edit_image_by_parameters_button_pressed',
                       'edit_image_by_reference_button_pressed', 'edit_image_with_sketch_button_pressed', 'edit_image_with_text_button_pressed',
                       'track_body_pose_button_pressed', 'filter_point_cloud_button_pressed', 'recolor_button_pressed', 'transfer_style_button_pressed',
                       'share_art_button_pressed', 'search_button_pressed', 'get_analytics_button_pressed', 'convert_speech_to_text_button_pressed',
                       'convert_text_to_speech_button_pressed', 'apply_objects_to_video_button_pressed', 'apply_effects_to_video_button_pressed',
                       'apply_effects_to_image_button_pressed', 'analyze_3d_scene_button_pressed', 'analyze_pdf_button_pressed',
                       'analyze_audio_button_pressed', 'analyze_video_button_pressed', 'analyze_document_button_pressed', 'analyze_image_button_pressed',
                       'analyze_content_button_pressed', 'analyze_website_button_pressed', 'check_for_plagiarism_button_pressed',
                       'colorize_button_pressed', 'recognize_face_button_pressed', 'recognize_text_button_pressed', 'upscale_image_button_pressed',
                       'summarize_content_button_pressed', 'rewrite_content_button_pressed', 'rewrite_articles_button_pressed',
                       'generate_music_button_pressed', 'generate_lines_button_pressed', 'segment_point_cloud_button_pressed',
                       'synthesize_voice_button_pressed', 'synchronize_lip_movements_with_video_button_pressed', 'create_3d_video_button_pressed',
                       'create_3d_object_button_pressed', 'create_3d_character_button_pressed', 'create_3d_scene_button_pressed',
                       'create_3d_texture_button_pressed', 'create_avatar_button_pressed', 'create_animation_button_pressed',
                       'create_audio_button_pressed', 'create_more_points_in_point_cloud_button_pressed', 'create_video_button_pressed',
                       'create_query_button_pressed', 'create_image_button_pressed', 'create_icons_button_pressed', 'create_depth_map_button_pressed',
                       'create_content_button_pressed', 'create_concept_button_pressed', 'create_logo_button_pressed', 'create_music_button_pressed',
                       'create_sketch_button_pressed', 'create_nudes_button_pressed', 'create_volumetric_video_button_pressed',
                       'create_volumetric_image_button_pressed', 'create_panorama_button_pressed', 'create_portrait_button_pressed',
                       'create_presentation_button_pressed', 'create_app_button_pressed', 'create_real_physical_animation_button_pressed',
                       'create_website_button_pressed', 'create_table_button_pressed', 'create_text_button_pressed', 'create_texture_button_pressed',
                       'create_background_button_pressed', 'create_chatbot_button_pressed', 'create_slowmo_effect_button_pressed',
                       'create_morphing_effect_button_pressed', 'match_audio_with_visuals_button_pressed', 'stabilize_video_button_pressed',
                       'stylize_button_pressed', 'remove_compression_button_pressed', 'remove_noise_button_pressed',
                       'remove_audio_noise_button_pressed', 'remove_watermark_button_pressed', 'remove_audio_segments_button_pressed',
                       'remove_object_button_pressed', 'remove_background_button_pressed', 'remove_background_in_video_button_pressed',
                       'enhance_query_button_pressed', 'enhance_video_quality_button_pressed', 'enhance_image_quality_button_pressed',
                       'enhance_night_photo_button_pressed', 'enhance_text_button_pressed', 'scale_down_image_button_pressed']


